import { useEffect, useRef, useState } from "react";
import { useRoomStore } from "./store";

declare global {
  interface Window {
    YT: any;
    onYouTubeIframeAPIReady: () => void;
  }
}

export function useAudioEngine() {
  const { playback, queue, sendAction } = useRoomStore();
  const playerRef = useRef<any>(null);
  const silentAudioRef = useRef<HTMLAudioElement | null>(null);
  
  const [hasInteracted, setHasInteracted] = useState(false);
  const [isBuffering, setIsBuffering] = useState(false);
  const [localProgress, setLocalProgress] = useState(0);
  const [isPlayerReady, setIsPlayerReady] = useState(false);

  // A very short silent MP3 base64 to "anchor" the Media Session on mobile.
  // This allows the browser to keep the tab active as an audio source and 
  // provides lock-screen controls even when the YouTube iframe pauses due to being hidden.
  const silentAudioBase64 = "data:audio/mpeg;base64,SUQzBAAAAAABAFRYWFgAAAASAAADbWFqb3JfYnJhbmQAZGFzaABUWFhYAAAAEQAAA21pbm9yX3ZlcnNpb24AMABUWFhYAAAAHAAAA2NvbXBhdGlibGVfYnJhbmRzAGlzbzZkYXNoAFRTU0UAAAAPAAADTGF2ZjYwLjMuMTAwAAAAAAAAAAAAAAD/+00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYaW5nAAAADwAAAAEAAAAAAAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUpLTE1OT1BSUlNVVldYWVpbXF1eX2BhYmNklJWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6u7y9vr/AwcLDxMXGx8jJysvMzc7P0NHS09TV1tfY2drb3N3e3+Di4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8AAAAA%20TGF2YwAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAAAP8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMf8O/7TQAAALAA6AEZAAAnS4AAG7CiwAAmF9oAABhR8YAMXMAAAMXMAAAEABeAAAMXMAAAAAAAA=";

export function useAudioEngine() {
  const { playback, queue, sendAction } = useRoomStore();
  const playerRef = useRef<any>(null);
  const silentAudioRef = useRef<HTMLAudioElement | null>(null);
  
  const [hasInteracted, setHasInteracted] = useState(false);
  const [isBuffering, setIsBuffering] = useState(false);
  const [localProgress, setLocalProgress] = useState(0);
  const [isPlayerReady, setIsPlayerReady] = useState(false);

  // Initialize YouTube IFrame API
  // It natively bypasses proxy IP bans using the user's browser securely,
  // and handles Safari interaction requirements.
  const initAudioContext = () => {
    if (hasInteracted) return;
    setHasInteracted(true);

    // Initialize silent audio element for background bridge
    const silent = new Audio(silentAudioBase64);
    silent.loop = true;
    silentAudioRef.current = silent;

    if (window.YT && window.YT.Player) {
      createPlayer();
    } else {
      // Inject YouTube API
      const tag = document.createElement('script');
      tag.src = "https://www.youtube.com/iframe_api";
      const firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode?.insertBefore(tag, firstScriptTag);

      window.onYouTubeIframeAPIReady = () => {
        createPlayer();
      };
    }
  };

  const createPlayer = () => {
    if (playerRef.current) return;
    
    // Create a hidden player div if it doesn't exist
    let playerDiv = document.getElementById("yt-player-container");
    if (!playerDiv) {
      playerDiv = document.createElement("div");
      playerDiv.id = "yt-player-container";
      playerDiv.style.position = "absolute";
      playerDiv.style.width = "1px";
      playerDiv.style.height = "1px";
      playerDiv.style.overflow = "hidden";
      playerDiv.style.pointerEvents = "none";
      playerDiv.style.top = "-100px";
      playerDiv.style.left = "-100px";
      playerDiv.style.opacity = "0.01"; // Keep it slightly visible to avoid aggressive throttle
      document.body.appendChild(playerDiv);
    }

    const currentTrack = useRoomStore.getState().queue.find(t => t.id === useRoomStore.getState().playback.currentTrackId);

    playerRef.current = new window.YT.Player("yt-player-container", {
      height: '64',
      width: '64',
      videoId: currentTrack?.id || '',
      playerVars: {
        playsinline: 1,
        controls: 0,
        disablekb: 1,
        rel: 0,
        fs: 0
      },
      events: {
        onReady: (event: any) => {
          setIsPlayerReady(true);
          // Auto-start if it was already "playing" in global state
          if (useRoomStore.getState().playback.isPlaying) {
             event.target.playVideo();
             silentAudioRef.current?.play().catch(() => {});
          }
        },
        onStateChange: (event: any) => {
          // YT.PlayerState.ENDED = 0
          if (event.data === 0) {
            sendAction({ type: "SKIP_NEXT" });
          }
          // YT.PlayerState.BUFFERING = 3
          setIsBuffering(event.data === 3);
        }
      }
    });

    // Local progress poller
    setInterval(() => {
      if (playerRef.current?.getCurrentTime) {
         setLocalProgress(playerRef.current.getCurrentTime());
      }
    }, 1000);
  };

  const loadedTrackId = useRef<string | null>(null);

  // Sync Logic wrapper around YouTube API
  useEffect(() => {
    if (!isPlayerReady || !playerRef.current) return;
    
    const player = playerRef.current;
    const currentTrack = queue.find(t => t.id === playback.currentTrackId);
    
    if (!currentTrack) {
      player.stopVideo();
      silentAudioRef.current?.pause();
      setLocalProgress(0);
      loadedTrackId.current = null;
      return;
    }

    try {
        // If track changed, strictly load exactly once
        if (loadedTrackId.current !== currentTrack.id) {
            player.loadVideoById(currentTrack.id);
            loadedTrackId.current = currentTrack.id;

            if ('mediaSession' in navigator) {
              navigator.mediaSession.metadata = new MediaMetadata({
                title: currentTrack.title,
                artist: currentTrack.channel,
                artwork: [{ src: currentTrack.thumbnail, sizes: '512x512', type: 'image/jpeg' }]
              });

              navigator.mediaSession.setActionHandler('play', () => {
                // Resume BOTH
                playerRef.current?.playVideo();
                silentAudioRef.current?.play().catch(() => {});
                sendAction({ type: "PLAY", offset: playerRef.current?.getCurrentTime() || 0 });
              });
              navigator.mediaSession.setActionHandler('pause', () => {
                playerRef.current?.pauseVideo();
                silentAudioRef.current?.pause();
                sendAction({ type: "PAUSE", offset: playerRef.current?.getCurrentTime() || 0 });
              });
              navigator.mediaSession.setActionHandler('nexttrack', () => {
                sendAction({ type: "SKIP_NEXT" });
              });
            }
        }

        const accurateServerOffset = playback.isPlaying 
          ? playback.trackOffset + (Date.now() - playback.startTimestamp) / 1000
          : playback.trackOffset;
        
        const currentTime = player.getCurrentTime ? player.getCurrentTime() : 0;
        const state = player.getPlayerState ? player.getPlayerState() : -1;
        
        // 1 = PLAYING, 2 = PAUSED. Do not seek if BUFFERING (3) or UNSTARTED (-1) to prevent loops!
        if ((state === 1 || state === 2) && Math.abs(currentTime - accurateServerOffset) > 2.0 && accurateServerOffset > 0) {
          player.seekTo(accurateServerOffset, true);
        }

        if (playback.isPlaying) {
          if (state !== 1 && state !== 3) {
            player.playVideo();
            silentAudioRef.current?.play().catch(() => {});
          }
        } else {
          if (state !== 2 && state !== 3 && state !== -1) {
            player.pauseVideo();
            silentAudioRef.current?.pause();
          }
        }
    } catch (err) {
        console.error("YT Player error:", err);
    }

  }, [playback.isPlaying, playback.currentTrackId, playback.startTimestamp, playback.trackOffset, isPlayerReady, queue]);

  return {
    initAudioContext,
    hasInteracted,
    isBuffering,
    localProgress,
    audioElement: null, // Legacy, no longer strictly native
  };
}
